// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function BrowseDir(arg1:string):Promise<main.BrowseResult>;

export function CreateProject(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetOutput(arg1:string):Promise<Array<string>>;

export function GetProjects():Promise<Array<config.Project>>;

export function GetRequests():Promise<main.RequestsResponse>;

export function GetServerInfo():Promise<main.ServerInfo>;

export function GetStatus():Promise<Array<main.StatusRow>>;

export function SetMACRules(arg1:string,arg2:Array<string>):Promise<void>;

export function StartProject(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StopProject(arg1:string):Promise<void>;

export function UpdateProject(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;
