// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseDir(arg1) {
  return window['go']['main']['App']['BrowseDir'](arg1);
}

export function CreateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3, arg4);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetOutput(arg1) {
  return window['go']['main']['App']['GetOutput'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetRequests() {
  return window['go']['main']['App']['GetRequests']();
}

export function GetServerInfo() {
  return window['go']['main']['App']['GetServerInfo']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function SetMACRules(arg1, arg2) {
  return window['go']['main']['App']['SetMACRules'](arg1, arg2);
}

export function StartProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartProject'](arg1, arg2, arg3);
}

export function StopProject(arg1) {
  return window['go']['main']['App']['StopProject'](arg1);
}

export function UpdateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3, arg4);
}
